# Generated by Django 2.1.5 on 2019-07-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.IntegerField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=30)),
            ],
        ),
    ]
