# Generated by Django 2.2.3 on 2019-07-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=30)),
                ('contact_phone', models.CharField(default='+880', max_length=14)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
