# Generated by Django 2.2.3 on 2019-07-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_contact_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_address',
            field=models.TextField(max_length=120),
        ),
    ]
